<?php
return array(
    'auth' => array(
        '0.3' => array('method' => 'rsa', 'key' => '234dfd'),
    ),

    //每个接口适用的版本
    'map' => array(
        'baby:add' => array(0.1),
        'baby:addrel' => array(0.1, 0.2),
        'baby:edit' => array(0.1,0.2),
        'baby:list' => array(0.1),
        'baby:invalid' => array(0.1),
        'baby:cancel' => array(0.1),
        'baby:steps' => array(0.1),
        'checkin:' => array(0.1),
        'comments:add' => array(0.1),
        'comments:list' => array(0.1),
        'comments:del' => array(0.1),
        'feedback:' => array(0.1),
        'fences:add' => array(0.1),
        'fences:edit' => array(0.1),
        'fences:del' => array(0.1),
        'fences:list' => array(0.1),
        'family:list' => array(0.1, 0.3),
        'family:gua' => array(0.1, 0.3),
        'family:add' => array(0.1, 0.3),
        'family:addRel' => array(0.1),
        'family:del' => array(0.1, 0.3),
        'feedback:' => array(0.1),
        'healthy:summary' => array(0.1),
        'healthy:list' => array(0.1, 0.3),
        'healthy:fore' => array(0.1),
        'locate:' => array(0.1, 0.3),
        'locate:day' => array(0.1, 0.3),
        'locate:shoecoor' => array(0.1),
        'locate:circle' => array(0.1),
        'locate:find' => array(0.1),
        'locate:upload' => array(0.3),
        'locate:delpic' => array(0.3),
        'lostpwd:captcha' => array(0.1),
        'lostpwd:reset' => array(0.1),
        'locus:list' => array(0.1),
        'locus:idlist' => array(0.3),
        'locus:callist' => array(0.1),
        'locus:message' => array(0.1),
        'locus:mark' => array(0.1),
        'locus:fresh' => array(0.1),
        'locus:remind' => array(0.1),
        'logs:android' => array(0.1),
        'myself:' =>array(0.1),
        'myself:disturb' => array(0.1),
        'mobile:captcha' => array(0.1),
        'msg:' => array(0.3),
        'msg:daily' => array(0.1),
        'msg:system' => array(0.1),
        'oauth:login' => array(0.1),
        'oauth:reg' => array(0.1),
        'oauth:bind' => array(0.1),
        'oauth:del' => array(0.1),
        'oauth:alipay' => array(0.1),
        'oauth:wechat' => array(0.1),
        'praises:add' => array(0.1),
        'praises:list' => array(0.1),
        'praises:del' => array(0.1),
        'push:binddev' => array(0.3),
        'pushmsg:system' => array(0.1),
        'pushmsg:interact' => array(0.1),
        'pushmsg:untoken' => array(0.1),
        'pushmsg:addfamily' => array(0.1),
        'pushmsg:bindQQ' => array(0.1),
        'renew:' => array(0.1),
        'renew:alipay' => array(0.1),
        'renew:wechat' => array(0.1),
        'rank:today' => array(0.1),
        'rank:all' => array(0.1),
        'ranking:' =>array(0.1),
        'shoe:add' => array(0.1, 0.3),
        'shoe:list' => array(0.1),
        'shoe:bind' => array(0.1),
        'shoe:unbind' => array(0.1),
        'shoe:mode' => array(0.1),
        'shoe:getmode' => array(0.1),
        'shoe:off' => array(0.1),
        'shoe:del' => array(0.1, 0.3),
        'tasks:cats' => array(0.1),
        'tasks:list' => array(0.1),
        'tasks:add' => array(0.1),
        'tasks:del' => array(0.1),
        'tasks:user' => array(0.1),
        'tasks:detail' => array(0.1),
        'tasks:ctasks' => array(0.1),
        'tasks:complete' => array(0.1),
        'union:add' => array(0.1, 0.2, 0.3),
        'union:checkuser' => array(0.1, 0.3),
        'user:reg' => array(0.1),
        'user:login' => array(0.1),
        'user:logout' => array(0.1),
        'user:edit' => array(0.1),
        'user:change' => array(0.1),
        'user:trial' => array(0.1),
        'ver:' => array(0.1),
        'ver:hardware' => array(0.1),
    ),

    //对应版本下废弃的接口
    'exclude' => array(
        '0.3' => array('baby:add')
    )
);